#!/usr/bin/env python3
import os
import re
import sys
from pathlib import Path

ENTRY_PATTERN = re.compile(r'\s*INCBIN\s*\(\s*([A-Za-z_][A-Za-z0-9_]*)\s*,\s*"([^"]+)"\s*\)\s*;')


def write_array(out, symbol, data):
    out.write(f"    extern const unsigned char g{symbol}Data[] = {{\n")
    for idx in range(0, len(data), 16):
        chunk = data[idx:idx + 16]
        out.write("        ")
        out.write(", ".join(f"0x{byte:02x}" for byte in chunk))
        out.write(",\n")
    out.write("    };\n")
    out.write(f"    extern const unsigned int g{symbol}Size = sizeof(g{symbol}Data);\n\n")
    out.write(f"    extern const unsigned char *const g{symbol}End = g{symbol}Data + sizeof(g{symbol}Data);\n")


def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <repository-root> <out-file>")
        return 1

    repo_root = Path(sys.argv[1]).resolve()
    out_file = Path(sys.argv[2]).resolve()
    rom_cxx = repo_root / "src" / "rom" / "rom.cxx"

    if not rom_cxx.exists():
        print(f"Error: could not find input file {rom_cxx}")
        return 1

    entries = []
    for line in rom_cxx.read_text().splitlines():
        match = ENTRY_PATTERN.match(line)
        if match:
            name, rel_path = match.groups()
            entries.append((name, rel_path))

    if not entries:
        print(f"Error: no INCBIN entries found in {rom_cxx}")
        return 1

    out_file.parent.mkdir(parents=True, exist_ok=True)
    with out_file.open("w", encoding="utf-8") as out:
        out.write("// Generated by tools/generate_rom_data.py. Do not edit directly.\n")
        out.write("#include <cstddef>\n\n")
        out.write("namespace ROM {\n")
        out.write("extern \"C\" {\n\n")

        for name, rel_path in entries:
            path = (repo_root / rel_path).resolve()
            if not path.exists():
                raise FileNotFoundError(f"Resource file not found: {path}")
            data = path.read_bytes()
            write_array(out, name, data)

        out.write("}\n")
        out.write("}\n")

    return 0


if __name__ == '__main__':
    raise SystemExit(main())
